"""sync models

Revision ID: 281df81c9edb
Revises: 6eb6e5b42247
Create Date: 2026-05-15 01:30:27.911505

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '281df81c9edb'
down_revision: Union[str, Sequence[str], None] = '6eb6e5b42247'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'disputes', ['order_id'])
    op.add_column('farmer_profiles', sa.Column('bvn', sa.String(), nullable=True))
    op.add_column('farmer_profiles', sa.Column('virtual_account_number', sa.String(), nullable=True))
    op.add_column('farmer_profiles', sa.Column('virtual_account_business_name', sa.String(), nullable=True))
    op.add_column('farmer_profiles', sa.Column('virtual_account_identifier', sa.String(), nullable=True))
    op.add_column('farmer_profiles', sa.Column('virtual_account_bank_code', sa.String(), nullable=True))
    op.add_column('farmer_profiles', sa.Column('virtual_account_bank_name', sa.String(), nullable=True))
    op.add_column('farmer_profiles', sa.Column('virtual_account_created_at', sa.DateTime(), nullable=True))
    op.add_column('farmer_profiles', sa.Column('virtual_account_is_active', sa.Boolean(), nullable=True))
    op.add_column('farmer_profiles', sa.Column('bvn_verified', sa.Boolean(), nullable=True))
    op.add_column('farmer_profiles', sa.Column('bvn_verified_at', sa.DateTime(), nullable=True))
    op.add_column('farmer_profiles', sa.Column('escrow_balance', sa.Numeric(precision=12, scale=2), nullable=True))
    op.add_column('farmer_profiles', sa.Column('settlement_account_number', sa.String(), nullable=True))
    op.add_column('farmer_profiles', sa.Column('settlement_bank_code', sa.String(), nullable=True))
    op.alter_column('farmer_profiles', 'total_sales',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=12, scale=2),
               existing_nullable=True)
    op.alter_column('farmer_profiles', 'rating',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=3, scale=2),
               existing_nullable=True)
    op.alter_column('order_items', 'price',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=12, scale=2),
               existing_nullable=True)
    op.add_column('orders', sa.Column('total_amount_kobo', sa.Integer(), nullable=True))
    op.add_column('orders', sa.Column('otp_hash', sa.String(), nullable=True))
    op.alter_column('orders', 'total_amount',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=12, scale=2),
               existing_nullable=True)
    op.alter_column('orders', 'delivery_fee',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=12, scale=2),
               existing_nullable=True)
    op.drop_column('orders', 'otp_code')
    op.add_column('payments', sa.Column('amount_kobo', sa.Integer(), nullable=True))
    op.add_column('payments', sa.Column('payout_reference', sa.String(), nullable=True))
    op.add_column('payments', sa.Column('payout_status', sa.String(), nullable=True))
    op.add_column('payments', sa.Column('payout_initiated_at', sa.DateTime(), nullable=True))
    op.alter_column('payments', 'amount',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=12, scale=2),
               existing_nullable=True)
    op.alter_column('payments', 'paid_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               existing_nullable=True)
    op.create_unique_constraint(None, 'payments', ['order_id'])
    op.create_unique_constraint(None, 'payments', ['payment_reference'])
    op.alter_column('products', 'price',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=12, scale=2),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('products', 'price',
               existing_type=sa.Numeric(precision=12, scale=2),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=False)
    op.drop_constraint(None, 'payments', type_='unique')
    op.drop_constraint(None, 'payments', type_='unique')
    op.alter_column('payments', 'paid_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               existing_nullable=True)
    op.alter_column('payments', 'amount',
               existing_type=sa.Numeric(precision=12, scale=2),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
    op.drop_column('payments', 'payout_initiated_at')
    op.drop_column('payments', 'payout_status')
    op.drop_column('payments', 'payout_reference')
    op.drop_column('payments', 'amount_kobo')
    op.add_column('orders', sa.Column('otp_code', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.alter_column('orders', 'delivery_fee',
               existing_type=sa.Numeric(precision=12, scale=2),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
    op.alter_column('orders', 'total_amount',
               existing_type=sa.Numeric(precision=12, scale=2),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
    op.drop_column('orders', 'otp_hash')
    op.drop_column('orders', 'total_amount_kobo')
    op.alter_column('order_items', 'price',
               existing_type=sa.Numeric(precision=12, scale=2),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
    op.alter_column('farmer_profiles', 'rating',
               existing_type=sa.Numeric(precision=3, scale=2),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
    op.alter_column('farmer_profiles', 'total_sales',
               existing_type=sa.Numeric(precision=12, scale=2),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
    op.drop_column('farmer_profiles', 'settlement_bank_code')
    op.drop_column('farmer_profiles', 'settlement_account_number')
    op.drop_column('farmer_profiles', 'escrow_balance')
    op.drop_column('farmer_profiles', 'bvn_verified_at')
    op.drop_column('farmer_profiles', 'bvn_verified')
    op.drop_column('farmer_profiles', 'virtual_account_is_active')
    op.drop_column('farmer_profiles', 'virtual_account_created_at')
    op.drop_column('farmer_profiles', 'virtual_account_bank_name')
    op.drop_column('farmer_profiles', 'virtual_account_bank_code')
    op.drop_column('farmer_profiles', 'virtual_account_identifier')
    op.drop_column('farmer_profiles', 'virtual_account_business_name')
    op.drop_column('farmer_profiles', 'virtual_account_number')
    op.drop_column('farmer_profiles', 'bvn')
    op.drop_constraint(None, 'disputes', type_='unique')
    # ### end Alembic commands ###
