"""initial_migration

Revision ID: 47e54e25fcdb
Revises: 
Create Date: 2026-03-27 00:14:06.826567

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '47e54e25fcdb'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('farmer_profiles', sa.Column('nin', sa.Integer(), nullable=False))
    op.add_column('farmer_profiles', sa.Column('bank_name', sa.String(), nullable=False))
    op.add_column('farmer_profiles', sa.Column('account_number', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('farmer_profiles', 'account_number')
    op.drop_column('farmer_profiles', 'bank_name')
    op.drop_column('farmer_profiles', 'nin')
    # ### end Alembic commands ###
