"""add price_kobo to order_items

Revision ID: 911533ce35fe
Revises: c17b308132c8
Create Date: 2026-05-15 04:44:12.961579

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '911533ce35fe'
down_revision: Union[str, Sequence[str], None] = 'c17b308132c8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order_items', sa.Column('price_kobo', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order_items', 'price_kobo')
    # ### end Alembic commands ###
