"""add delivery_fee_kobo

Revision ID: c17b308132c8
Revises: 281df81c9edb
Create Date: 2026-05-15 04:14:42.877112

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c17b308132c8'
down_revision: Union[str, Sequence[str], None] = '281df81c9edb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('farmer_profiles', 'nin',
               existing_type=sa.BIGINT(),
               type_=sa.String(),
               existing_nullable=False)
    op.add_column('orders', sa.Column('delivery_fee_kobo', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'delivery_fee_kobo')
    op.alter_column('farmer_profiles', 'nin',
               existing_type=sa.String(),
               type_=sa.BIGINT(),
               existing_nullable=False)
    # ### end Alembic commands ###
